# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitmorph" do
  name "gitmorph"
  desc ""
  homepage "https://github.com/abhigyan-mohanta/gitmorph"
  version "3.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitmorph"

  on_macos do
    url "https://github.com/ABHIGYAN-MOHANTA/gitmorph/releases/download/v#{version}/gitmorph_#{version}_darwin_all.tar.gz"
    sha256 "43d92c6940b4dd480b7c7755c8f3410ff6b9b242ceac4d3000b1e5fa81407cec"
  end

  # No zap stanza required
end
